# Generated by Django 2.2 on 2020-11-17 11:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('vehicle_name', models.CharField(default='', max_length=100)),
                ('vehicle_type', models.CharField(default='', max_length=100)),
                ('vehicle_price', models.FloatField()),
                ('vehicle_brand', models.CharField(default='', max_length=60)),
                ('vehicle_model', models.CharField(default='', max_length=30)),
                ('vehicle_status', models.CharField(default='', max_length=30)),
                ('inventoryadmincontact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'Vehicle',
            },
        ),
        migrations.CreateModel(
            name='VehicleAvailability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('vehicle_availabilityStatus', models.CharField(default='', max_length=100)),
                ('vehicle_availabilityComments', models.CharField(default='', max_length=200)),
                ('vehicle_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicleavails', to='vehiclemsapp.Vehicle')),
            ],
            options={
                'verbose_name': 'VehicleAvailability',
                'verbose_name_plural': 'VehicleAvailability',
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('purchaseorder_date', models.DateTimeField()),
                ('totalnumberordered', models.IntegerField()),
                ('purchaseorder_status', models.CharField(default='', max_length=30)),
                ('suppliercontact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vehicle_availabilityId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchaseorders', to='vehiclemsapp.VehicleAvailability')),
                ('vehicle_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='vehiclemsapp.Vehicle')),
            ],
            options={
                'verbose_name': 'PurchaseOrder',
                'verbose_name_plural': 'PurchaseOrder',
            },
        ),
        migrations.CreateModel(
            name='BillingOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('billingorder_price', models.FloatField()),
                ('billingorder_status', models.CharField(blank=True, max_length=30, null=True)),
                ('billingorder_date', models.DateTimeField()),
                ('purchaseorder_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billingorders', to='vehiclemsapp.PurchaseOrder')),
            ],
            options={
                'verbose_name': 'BillingOrder',
                'verbose_name_plural': 'BillingOrder',
            },
        ),
    ]
