# Generated by Django 2.2 on 2020-11-17 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehiclemsapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billingorder',
            old_name='purchaseorder_Id',
            new_name='purchaseorder_details',
        ),
        migrations.RenameField(
            model_name='purchaseorder',
            old_name='vehicle_availabilityId',
            new_name='vehicle_availability',
        ),
    ]
