# Generated by Django 2.2 on 2020-11-17 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiclemsapp', '0002_auto_20201117_1702'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseorder',
            old_name='suppliercontact',
            new_name='supplier_contact',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='inventoryadmincontact',
            new_name='inventory_admincontact',
        ),
        migrations.RenameField(
            model_name='vehicleavailability',
            old_name='vehicle_availabilityComments',
            new_name='vehicle_availability_comments',
        ),
        migrations.RenameField(
            model_name='vehicleavailability',
            old_name='vehicle_availabilityStatus',
            new_name='vehicle_availability_status',
        ),
        migrations.AlterField(
            model_name='billingorder',
            name='billingorder_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='purchaseorder_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
